spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/wordpuzzle
        username: wordist
        password: itsapuzzle
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            show_sql: true
            ddl-auto: update